### ISSUE TITLE
download the data, including trained models

### ISSUE THREAD

**Issue by nara516** [ad-freiburg/tokenization-repair#5]
Hello

I can't download the data, including trained models. (used the command "make download-data")
I executed this command, but I get to 404 Error.
How can I download the data?

Thank you.

**Comment by hertelm** [comment]
Hi, thank you very much for reporting this error! The data can now be downloaded from [here](https://ad-publications.informatik.uni-freiburg.de/CoNLL_tokenization_repair_BHM_2021.materials/data.zip) and the Makefile is updated accordingly.

You might be interested in our new whitespace correction method based on Transformer neural networks, which gives equally good results about 300 times faster. See the [webpage](https://whitespace-correction.cs.uni-freiburg.de/) and [repository](https://github.com/ad-freiburg/whitespace-correction) with instructions (e.g. how to install it with a single pip command).
